# CMake generated Testfile for 
# Source directory: /home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control
# Build directory: /home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/cmake-cache/examples/traffic-control
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-traffic-control "ns3.41-traffic-control-optimized")
set_tests_properties(ctest-traffic-control PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;1;build_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-queue-discs-benchmark "ns3.41-queue-discs-benchmark-optimized")
set_tests_properties(ctest-queue-discs-benchmark PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;12;build_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-fengadaptive "ns3.41-red-vs-fengadaptive-optimized")
set_tests_properties(ctest-red-vs-fengadaptive PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;24;build_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-nlred "ns3.41-red-vs-nlred-optimized")
set_tests_properties(ctest-red-vs-nlred PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;35;build_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-tbf-example "ns3.41-tbf-example-optimized")
set_tests_properties(ctest-tbf-example PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;46;build_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-cobalt-vs-codel "ns3.41-cobalt-vs-codel-optimized")
set_tests_properties(ctest-cobalt-vs-codel PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/macros-and-definitions.cmake;1392;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;56;build_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/examples/traffic-control/CMakeLists.txt;0;")
