# CMake generated Testfile for 
# Source directory: /home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples
# Build directory: /home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/cmake-cache/src/stats/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-time-probe-example "ns3.41-time-probe-example-optimized")
set_tests_properties(ctest-time-probe-example PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;1;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-example "ns3.41-gnuplot-example-optimized")
set_tests_properties(ctest-gnuplot-example PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-double-probe-example "ns3.41-double-probe-example-optimized")
set_tests_properties(ctest-double-probe-example PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-aggregator-example "ns3.41-gnuplot-aggregator-example-optimized")
set_tests_properties(ctest-gnuplot-aggregator-example PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-helper-example "ns3.41-gnuplot-helper-example-optimized")
set_tests_properties(ctest-gnuplot-helper-example PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-aggregator-example "ns3.41-file-aggregator-example-optimized")
set_tests_properties(ctest-file-aggregator-example PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-helper-example "ns3.41-file-helper-example-optimized")
set_tests_properties(ctest-file-helper-example PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/stats/examples/CMakeLists.txt;0;")
