# CMake generated Testfile for 
# Source directory: /home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils
# Build directory: /home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/cmake-cache/utils
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-test-runner "ns3.41-test-runner-optimized")
set_tests_properties(ctest-test-runner PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/utils/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;44;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;0;")
add_test(ctest-bench-scheduler "ns3.41-bench-scheduler-optimized")
set_tests_properties(ctest-bench-scheduler PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/utils/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;51;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;0;")
add_test(ctest-bench-packets "ns3.41-bench-packets-optimized")
set_tests_properties(ctest-bench-packets PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/utils/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;59;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;0;")
add_test(ctest-print-introspected-doxygen "ns3.41-print-introspected-doxygen-optimized")
set_tests_properties(ctest-print-introspected-doxygen PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/utils/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;66;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;0;")
add_test(ctest-perf-io "ns3.41-perf-io-optimized")
set_tests_properties(ctest-perf-io PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/utils/perf/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;75;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/utils/CMakeLists.txt;0;")
