# CMake generated Testfile for 
# Source directory: /home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/sixlowpan/examples
# Build directory: /home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/cmake-cache/src/sixlowpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-example-sixlowpan "ns3.41-example-sixlowpan-optimized")
set_tests_properties(ctest-example-sixlowpan PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/sixlowpan/examples/CMakeLists.txt;1;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan "ns3.41-example-ping-lr-wpan-optimized")
set_tests_properties(ctest-example-ping-lr-wpan PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/sixlowpan/examples/CMakeLists.txt;12;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-beacon "ns3.41-example-ping-lr-wpan-beacon-optimized")
set_tests_properties(ctest-example-ping-lr-wpan-beacon PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/sixlowpan/examples/CMakeLists.txt;23;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-mesh-under "ns3.41-example-ping-lr-wpan-mesh-under-optimized")
set_tests_properties(ctest-example-ping-lr-wpan-mesh-under PROPERTIES  WORKING_DIRECTORY "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/sixlowpan/examples/CMakeLists.txt;34;build_lib_example;/home/ericksbp/Tesis_TVWS/ns-allinone-3.41/ns-3.41/src/sixlowpan/examples/CMakeLists.txt;0;")
